/* Middleware Actions */
/* Socket Connection Actions */
export const ESTABLISH_SOCKET_CONNECTION = "ESTABLISH_SOCKET_CONNECTION";
export const SET_SOCKET_CONNECTION = "SET_SOCKET_CONNECTION";
export const TERMINATE_SOCKET_CONNECTION = "TERMINATE_SOCKET_CONNECTION";

/* AUTH Middleware Actions */
export const AUTH_STATUS_CHANGE = "AUTH_STATUS_CHANGE";
export const SET_AUTH_CONSTRUCTOR = "SET_AUTH_CONSTRUCTOR";
export const SET_AUTH_NONCE = "SET_AUTH_NONCE";

/* App Actions */
/* Facility(s) Actions */
export const CREATE_FACILITY_SUCCESS = "CREATE_FACILITY_SUCCESS";
export const DELETE_FACILITY_SUCCESS = "DELETE_FACILITY_SUCCESS";
export const GET_FACILITY_SUCCESS = "GET_FACILITY_SUCCESS";
export const RESET_FACILITIES_SUCCESS = "RESET_FACILITIES_SUCCESS";
export const SEARCH_FACILITIES_SUCCESS = "SEARCH_FACILITIES_SUCCESS";
export const UPDATE_FACILITY_SUCCESS = "UPDATE_FACILITY_SUCCESS";

/* Gig(s) Actions */
export const CREATE_GIG_SUCCESS = "CREATE_GIG_SUCCESS";
export const DELETE_GIG_SUCCESS = "DELETE_GIG_SUCCESS";
export const GET_GIG_SUCCESS = "GET_GIG_SUCCESS";
export const RESET_GIGS_SUCCESS = "RESET_GIGS_SUCCESS";
export const SEARCH_GIGS_SUCCESS = "SEARCH_GIGS_SUCCESS";
export const UPDATE_GIG_SUCCESS = "UPDATE_GIG_SUCCESS";

/* Housing(s) Actions */
export const CREATE_HOUSING_SUCCESS = "CREATE_HOUSING_SUCCESS";
export const DELETE_HOUSING_SUCCESS = "DELETE_HOUSING_SUCCESS";
export const GET_HOUSING_SUCCESS = "GET_HOUSING_SUCCESS";
export const RESET_HOUSING_SUCCESS = "RESET_HOUSING_SUCCESS";
export const SEARCH_HOUSING_SUCCESS = "SEARCH_HOUSING_SUCCESS";
export const UPDATE_HOUSING_SUCCESS = "UPDATE_HOUSING_SUCCESS";

/* Member(s) Actions */
export const ADD_MEMBERS_SUCCESS = "ADD_MEMBERS_SUCCESS";
export const CREATE_MEMBER_SUCCESS = "CREATE_MEMBER_SUCCESS";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const RESET_MEMBER_PASSWORD_SUCCESS = "RESET_MEMBER_PASSWORD_SUCCESS";
export const RESET_MEMBERS_SUCCESS = "RESET_MEMBERS_SUCCESS";
export const SEARCH_MEMBERS_SUCCESS = "SEARCH_MEMBERS_SUCCESS";
export const SET_ACTIVE_MEMBER_SUCCESS = "SET_ACTIVE_MEMBER_SUCCESS";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";

/* Plan(s) Actions */
export const SEARCH_PLANS_SUCCESS = "SEARCH_PLANS_SUCCESS";

/* Toggle Everything */
export const TOGGLE_ABOUT_MODAL = "TOGGLE_ABOUT_MODAL";
export const TOGGLE_EXPERIENCE_MODAL = "TOGGLE_EXPERIENCE_MODAL";
export const TOGGLE_FILTER_MODAL = "TOGGLE_FILTER_MODAL";
export const TOGGLE_LICENSE_MODAL = "TOGGLE_LICENSE_MODAL";
export const TOGGLE_PROFILE_MODAL = "TOGGLE_PROFILE_MODAL";
export const TOGGLE_NOTIFICATION_MODAL = "TOGGLE_NOTIFICATION_MODAL";

/* Profile Actions */
export const DELETE_LICENSE_SUCCESS = "DELETE_LICENSE_SUCCESS";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";
export const GET_ABOUT_SUCCESS = "GET_ABOUT_SUCCESS";
export const GET_EXPERIENCE_SUCCESS = "GET_EXPERIENCE_SUCCESS";
export const GET_LICENSE_SUCCESS = "GET_LICENSE_SUCCESS";
export const UPDATE_ABOUT_SUCCESS = "UPDATE_ABOUT_SUCCESS";
export const UPDATE_EXPERIENCE_SUCCESS = "UPDATE_EXPERIENCE_SUCCESS";
export const UPDATE_LICENSE_SUCCESS = "UPDATE_LICENSE_SUCCESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

/* Sidebar Actions */
export const UPDATE_SIDEBAR_SELECTOR_SUCCESS =
  "UPDATE_SIDEBAR_SELECTOR_SUCCESS";
export const UPDATE_SIDEBAR_SET_SUCCESS = "UPDATE_SIDEBAR_SET_SUCCESS";
